language: python

matrix:
  include:
    - os: linux
      language: python
    - os: osx
      language: generic

addons:
  apt:
    packages:
      - gcc
      - libssl-dev
      - libsqlite3-dev
      - uuid-dev

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then virtualenv -p /usr/local/bin/python venv; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then . ./venv/bin/activate; fi

install:
  # Required for OS X. Not restricted by TRAVIS_OS_NAME because including an
  # `install` section overrides the implicit `pip install` on Linux.
  - pip install -r requirements.txt

script: make test

notifications:
  email: false
