language: python
python:
  - '3.6'

matrix:
  include:
    - os: linux
    - os: osx
      language: generic
      # This is a hack to set up tox-travis on OS X, since this is a generic
      # build. Travis sets this automatically for Python builds.
      env: TRAVIS_PYTHON_VERSION=3.6

addons:
  apt:
    packages:
      - gcc
      - libssl-dev
      - libsqlite3-dev
      - uuid-dev

before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    pyenv install 3.6.5
    pyenv global 3.6.5
  fi

install:
  - pip install tox-travis

script:
  - make DEBUG=1
  - make test USE_DEFAULT_ENTRY_POINT=1

after_success: |
  if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    gcov src/uuid.c
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  email: false
